-- Add analysis fields to call_history table
-- These fields will store call analysis data generated by the assistant

ALTER TABLE public.call_history 
ADD COLUMN IF NOT EXISTS call_summary TEXT,
ADD COLUMN IF NOT EXISTS success_evaluation TEXT,
ADD COLUMN IF NOT EXISTS structured_data JSONB DEFAULT '{}'::jsonb;

-- Add comments for documentation
COMMENT ON COLUMN public.call_history.call_summary IS 'AI-generated summary of the call conversation';
COMMENT ON COLUMN public.call_history.success_evaluation IS 'AI evaluation of call success/failure';
COMMENT ON COLUMN public.call_history.structured_data IS 'Structured data extracted from the call (JSONB)';

-- Create index for better query performance on structured data
CREATE INDEX IF NOT EXISTS idx_call_history_structured_data ON public.call_history USING GIN(structured_data) 
WHERE structured_data IS NOT NULL AND jsonb_typeof(structured_data) = 'object';
